### ISSUE TITLE
System Diagrams: Design UML Diagram

### ISSUE THREAD

**Issue by sywong888** [nidhigiridhar/cse110-w21-group35#4]
# System Diagrams: Design UML Diagram

## Completion Requirements:  
* This diagram, with the C4 and event modeling diagrams, should describe the whole system
* Should be completed after the C4 diagram is finished

## Links/Resources  
https://en.wikipedia.org/wiki/Unified_Modeling_Language#Diagrams

**Comment by nidhigiridhar** [comment]
Decided that this was not needed since we have the structure diagram in the C4 component diagram and the behavioral diagram in the event model diagram
